package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asistenciaevt generated by hbm2java
 */
@Entity
@Table(name="asistenciaevt"
    ,catalog="dbcrm"
)
public class Asistenciaevt  implements java.io.Serializable {


     private Integer idAsistenciaevt;
     private Evento evento;
     private String astPresentes;
     private String astFaltas;
     private String astVisitas;
     private String astDescripcion;
     private String astLugar;
     private Set<Asmiemmin> asmiemmins = new HashSet<>(0);
     private Set<Asmiemgp> asmiemgps = new HashSet<>(0);

    public Asistenciaevt() {
    }

	
    public Asistenciaevt(Evento evento, String astPresentes, String astFaltas, String astVisitas) {
        this.evento = evento;
        this.astPresentes = astPresentes;
        this.astFaltas = astFaltas;
        this.astVisitas = astVisitas;
    }
    public Asistenciaevt(Evento evento, String astPresentes, String astFaltas, String astVisitas, String astDescripcion, String astLugar, Set<Asmiemmin> asmiemmins, Set<Asmiemgp> asmiemgps) {
       this.evento = evento;
       this.astPresentes = astPresentes;
       this.astFaltas = astFaltas;
       this.astVisitas = astVisitas;
       this.astDescripcion = astDescripcion;
       this.astLugar = astLugar;
       this.asmiemmins = asmiemmins;
       this.asmiemgps = asmiemgps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idASISTENCIAEVT", unique=true, nullable=false)
    public Integer getIdAsistenciaevt() {
        return this.idAsistenciaevt;
    }
    
    public void setIdAsistenciaevt(Integer idAsistenciaevt) {
        this.idAsistenciaevt = idAsistenciaevt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEVENTO", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    
    @Column(name="AST_PRESENTES", nullable=false, length=64)
    public String getAstPresentes() {
        return this.astPresentes;
    }
    
    public void setAstPresentes(String astPresentes) {
        this.astPresentes = astPresentes;
    }

    
    @Column(name="AST_FALTAS", nullable=false, length=64)
    public String getAstFaltas() {
        return this.astFaltas;
    }
    
    public void setAstFaltas(String astFaltas) {
        this.astFaltas = astFaltas;
    }

    
    @Column(name="AST_VISITAS", nullable=false, length=64)
    public String getAstVisitas() {
        return this.astVisitas;
    }
    
    public void setAstVisitas(String astVisitas) {
        this.astVisitas = astVisitas;
    }

    
    @Column(name="AST_DESCRIPCION")
    public String getAstDescripcion() {
        return this.astDescripcion;
    }
    
    public void setAstDescripcion(String astDescripcion) {
        this.astDescripcion = astDescripcion;
    }

    
    @Column(name="AST_LUGAR")
    public String getAstLugar() {
        return this.astLugar;
    }
    
    public void setAstLugar(String astLugar) {
        this.astLugar = astLugar;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asistenciaevt")
    public Set<Asmiemmin> getAsmiemmins() {
        return this.asmiemmins;
    }
    
    public void setAsmiemmins(Set<Asmiemmin> asmiemmins) {
        this.asmiemmins = asmiemmins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asistenciaevt")
    public Set<Asmiemgp> getAsmiemgps() {
        return this.asmiemgps;
    }
    
    public void setAsmiemgps(Set<Asmiemgp> asmiemgps) {
        this.asmiemgps = asmiemgps;
    }




}


