package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asmiemgp generated by hbm2java
 */
@Entity
@Table(name="asmiemgp"
    ,catalog="dbcrm"
)
public class Asmiemgp  implements java.io.Serializable {


     private Integer idAsmiemgp;
     private Asistenciaevt asistenciaevt;
     private Miembrogp miembrogp;
     private String asgAsistencia;

    public Asmiemgp() {
    }

    public Asmiemgp(Asistenciaevt asistenciaevt, Miembrogp miembrogp, String asgAsistencia) {
       this.asistenciaevt = asistenciaevt;
       this.miembrogp = miembrogp;
       this.asgAsistencia = asgAsistencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idASMIEMGP", unique=true, nullable=false)
    public Integer getIdAsmiemgp() {
        return this.idAsmiemgp;
    }
    
    public void setIdAsmiemgp(Integer idAsmiemgp) {
        this.idAsmiemgp = idAsmiemgp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idASISTENCIAEVT", nullable=false)
    public Asistenciaevt getAsistenciaevt() {
        return this.asistenciaevt;
    }
    
    public void setAsistenciaevt(Asistenciaevt asistenciaevt) {
        this.asistenciaevt = asistenciaevt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMIEMBROGP", nullable=false)
    public Miembrogp getMiembrogp() {
        return this.miembrogp;
    }
    
    public void setMiembrogp(Miembrogp miembrogp) {
        this.miembrogp = miembrogp;
    }

    
    @Column(name="ASG_ASISTENCIA", nullable=false, length=1)
    public String getAsgAsistencia() {
        return this.asgAsistencia;
    }
    
    public void setAsgAsistencia(String asgAsistencia) {
        this.asgAsistencia = asgAsistencia;
    }




}


