package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asmiemmin generated by hbm2java
 */
@Entity
@Table(name="asmiemmin"
    ,catalog="dbcrm"
)
public class Asmiemmin  implements java.io.Serializable {


     private Integer idAsmiemmin;
     private Asistenciaevt asistenciaevt;
     private Miembromin miembromin;
     private Integer asmAsistencia;

    public Asmiemmin() {
    }

	
    public Asmiemmin(Asistenciaevt asistenciaevt, Miembromin miembromin) {
        this.asistenciaevt = asistenciaevt;
        this.miembromin = miembromin;
    }
    public Asmiemmin(Asistenciaevt asistenciaevt, Miembromin miembromin, Integer asmAsistencia) {
       this.asistenciaevt = asistenciaevt;
       this.miembromin = miembromin;
       this.asmAsistencia = asmAsistencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idASMIEMMIN", unique=true, nullable=false)
    public Integer getIdAsmiemmin() {
        return this.idAsmiemmin;
    }
    
    public void setIdAsmiemmin(Integer idAsmiemmin) {
        this.idAsmiemmin = idAsmiemmin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idASISTENCIAEVT", nullable=false)
    public Asistenciaevt getAsistenciaevt() {
        return this.asistenciaevt;
    }
    
    public void setAsistenciaevt(Asistenciaevt asistenciaevt) {
        this.asistenciaevt = asistenciaevt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMIEMBROMIN", nullable=false)
    public Miembromin getMiembromin() {
        return this.miembromin;
    }
    
    public void setMiembromin(Miembromin miembromin) {
        this.miembromin = miembromin;
    }

    
    @Column(name="ASM_ASISTENCIA")
    public Integer getAsmAsistencia() {
        return this.asmAsistencia;
    }
    
    public void setAsmAsistencia(Integer asmAsistencia) {
        this.asmAsistencia = asmAsistencia;
    }




}


