package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 11:55:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detrol generated by hbm2java
 */
@Entity
@Table(name="detrol"
    ,catalog="dbcrm"
)
public class Detrol  implements java.io.Serializable {


     private Integer idDetrol;
     private Rol rol;
     private Usuario usuario;
     private String drlEstado;

    public Detrol() {
    }

    public Detrol(Rol rol, Usuario usuario, String drlEstado) {
       this.rol = rol;
       this.usuario = usuario;
       this.drlEstado = drlEstado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDETROL", unique=true, nullable=false)
    public Integer getIdDetrol() {
        return this.idDetrol;
    }
    
    public void setIdDetrol(Integer idDetrol) {
        this.idDetrol = idDetrol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUSUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="DRL_ESTADO", nullable=false, length=1)
    public String getDrlEstado() {
        return this.drlEstado;
    }
    
    public void setDrlEstado(String drlEstado) {
        this.drlEstado = drlEstado;
    }




}


