package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detrol generated by hbm2java
 */
@Entity
@Table(name="detrol"
    ,catalog="dbcrm"
)
public class Detrol  implements java.io.Serializable {


     private Integer idDetrol;
     private Rol rol;
     private Usuario usuario;
     private String drlEstado;
     private Date drlFechaAdd;
     private Date drlFechaUpd;
     private Date drlFechaDel;
     private int drlUsuAdd;
     private Integer drlUsuUpd;
     private Integer drlUsuDel;

    public Detrol() {
    }

	
    public Detrol(Rol rol, Usuario usuario, String drlEstado, Date drlFechaAdd, int drlUsuAdd) {
        this.rol = rol;
        this.usuario = usuario;
        this.drlEstado = drlEstado;
        this.drlFechaAdd = drlFechaAdd;
        this.drlUsuAdd = drlUsuAdd;
    }
    public Detrol(Rol rol, Usuario usuario, String drlEstado, Date drlFechaAdd, Date drlFechaUpd, Date drlFechaDel, int drlUsuAdd, Integer drlUsuUpd, Integer drlUsuDel) {
       this.rol = rol;
       this.usuario = usuario;
       this.drlEstado = drlEstado;
       this.drlFechaAdd = drlFechaAdd;
       this.drlFechaUpd = drlFechaUpd;
       this.drlFechaDel = drlFechaDel;
       this.drlUsuAdd = drlUsuAdd;
       this.drlUsuUpd = drlUsuUpd;
       this.drlUsuDel = drlUsuDel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDETROL", unique=true, nullable=false)
    public Integer getIdDetrol() {
        return this.idDetrol;
    }
    
    public void setIdDetrol(Integer idDetrol) {
        this.idDetrol = idDetrol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUSUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="DRL_ESTADO", nullable=false, length=1)
    public String getDrlEstado() {
        return this.drlEstado;
    }
    
    public void setDrlEstado(String drlEstado) {
        this.drlEstado = drlEstado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRL_FECHA_ADD", nullable=false, length=19)
    public Date getDrlFechaAdd() {
        return this.drlFechaAdd;
    }
    
    public void setDrlFechaAdd(Date drlFechaAdd) {
        this.drlFechaAdd = drlFechaAdd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRL_FECHA_UPD", length=19)
    public Date getDrlFechaUpd() {
        return this.drlFechaUpd;
    }
    
    public void setDrlFechaUpd(Date drlFechaUpd) {
        this.drlFechaUpd = drlFechaUpd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRL_FECHA_DEL", length=19)
    public Date getDrlFechaDel() {
        return this.drlFechaDel;
    }
    
    public void setDrlFechaDel(Date drlFechaDel) {
        this.drlFechaDel = drlFechaDel;
    }

    
    @Column(name="DRL_USU_ADD", nullable=false)
    public int getDrlUsuAdd() {
        return this.drlUsuAdd;
    }
    
    public void setDrlUsuAdd(int drlUsuAdd) {
        this.drlUsuAdd = drlUsuAdd;
    }

    
    @Column(name="DRL_USU_UPD")
    public Integer getDrlUsuUpd() {
        return this.drlUsuUpd;
    }
    
    public void setDrlUsuUpd(Integer drlUsuUpd) {
        this.drlUsuUpd = drlUsuUpd;
    }

    
    @Column(name="DRL_USU_DEL")
    public Integer getDrlUsuDel() {
        return this.drlUsuDel;
    }
    
    public void setDrlUsuDel(Integer drlUsuDel) {
        this.drlUsuDel = drlUsuDel;
    }




}


