package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 11:55:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name="documento"
    ,catalog="dbcrm"
)
public class Documento  implements java.io.Serializable {


     private Integer idDocumento;
     private String docDescripcion;
     private String docNombreCorto;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Documento() {
    }

	
    public Documento(String docDescripcion, String docNombreCorto) {
        this.docDescripcion = docDescripcion;
        this.docNombreCorto = docNombreCorto;
    }
    public Documento(String docDescripcion, String docNombreCorto, Set<Persona> personas) {
       this.docDescripcion = docDescripcion;
       this.docNombreCorto = docNombreCorto;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDOCUMENTO", unique=true, nullable=false)
    public Integer getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(Integer idDocumento) {
        this.idDocumento = idDocumento;
    }

    
    @Column(name="DOC_DESCRIPCION", nullable=false, length=64)
    public String getDocDescripcion() {
        return this.docDescripcion;
    }
    
    public void setDocDescripcion(String docDescripcion) {
        this.docDescripcion = docDescripcion;
    }

    
    @Column(name="DOC_NOMBRE_CORTO", nullable=false, length=16)
    public String getDocNombreCorto() {
        return this.docNombreCorto;
    }
    
    public void setDocNombreCorto(String docNombreCorto) {
        this.docNombreCorto = docNombreCorto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documento")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


