package pe.edu.upeu.crm.bean;
// Generated 11/11/2017 08:16:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventoministerioId generated by hbm2java
 */
@Embeddable
public class EventoministerioId  implements java.io.Serializable {


     private int idMinisterio;
     private int idEvento;

    public EventoministerioId() {
    }

    public EventoministerioId(int idMinisterio, int idEvento) {
       this.idMinisterio = idMinisterio;
       this.idEvento = idEvento;
    }
   


    @Column(name="idMINISTERIO", nullable=false)
    public int getIdMinisterio() {
        return this.idMinisterio;
    }
    
    public void setIdMinisterio(int idMinisterio) {
        this.idMinisterio = idMinisterio;
    }


    @Column(name="idEVENTO", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventoministerioId) ) return false;
		 EventoministerioId castOther = ( EventoministerioId ) other; 
         
		 return (this.getIdMinisterio()==castOther.getIdMinisterio())
 && (this.getIdEvento()==castOther.getIdEvento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMinisterio();
         result = 37 * result + this.getIdEvento();
         return result;
   }   


}


