package pe.edu.upeu.crm.bean;
// Generated 11/11/2017 08:16:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventogrupo generated by hbm2java
 */
@Entity
@Table(name="eventogrupo"
    ,catalog="dbcrm"
)
public class Eventogrupo  implements java.io.Serializable {


     private EventogrupoId id;
     private Integer evgPresentes;
     private Integer evgFaltas;
     private Integer evgVisitas;
     private String evgDescripcion;
     private String evgLugar;
     private Date evgFechaRegistro;
     private String evgEstado;

    public Eventogrupo() {
    }

	
    public Eventogrupo(EventogrupoId id) {
        this.id = id;
    }

   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idGrupo", column=@Column(name="idGRUPO", nullable=false) ), 
        @AttributeOverride(name="idEvento", column=@Column(name="idEVENTO", nullable=false) ) } )
    public EventogrupoId getId() {
        return this.id;
    }
    
    public void setId(EventogrupoId id) {
        this.id = id;
    }

    
    @Column(name="EVG_PRESENTES")
    public Integer getEvgPresentes() {
        return this.evgPresentes;
    }
    
    public void setEvgPresentes(Integer evgPresentes) {
        this.evgPresentes = evgPresentes;
    }

    
    @Column(name="EVG_FALTAS")
    public Integer getEvgFaltas() {
        return this.evgFaltas;
    }
    
    public void setEvgFaltas(Integer evgFaltas) {
        this.evgFaltas = evgFaltas;
    }

    
    @Column(name="EVG_VISITAS")
    public Integer getEvgVisitas() {
        return this.evgVisitas;
    }
    
    public void setEvgVisitas(Integer evgVisitas) {
        this.evgVisitas = evgVisitas;
    }

    
    @Column(name="EVG_DESCRIPCION")
    public String getEvgDescripcion() {
        return this.evgDescripcion;
    }
    
    public void setEvgDescripcion(String evgDescripcion) {
        this.evgDescripcion = evgDescripcion;
    }

    
    @Column(name="EVG_LUGAR")
    public String getEvgLugar() {
        return this.evgLugar;
    }
    
    public void setEvgLugar(String evgLugar) {
        this.evgLugar = evgLugar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EVG_FECHA_REGISTRO", length=19)
    public Date getEvgFechaRegistro() {
        return this.evgFechaRegistro;
    }
    
    public void setEvgFechaRegistro(Date evgFechaRegistro) {
        this.evgFechaRegistro = evgFechaRegistro;
    }

    
    @Column(name="EVG_ESTADO", length=1)
    public String getEvgEstado() {
        return this.evgEstado;
    }
    
    public void setEvgEstado(String evgEstado) {
        this.evgEstado = evgEstado;
    }




}


