package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", catalog = "dbcrm"
)
public class Evento implements java.io.Serializable {

    private Integer idEvento;
    private int idTipoevento;
    private int idPeriodo;
    private String evtNombre;
    private String evtDescripcion;
    private String evtLugar;
    private Date evtFecha;
    private Date evtFechaLimite;
    private int evtDistrito;
    private int evtIglesia;
    private String evtEstado;
    private int evtUsuAdd;
    private Integer evtUsuUpd;
    private Integer evtUsuEli;
    private Date evtFechaAdd;
    private Date evtFechaUpd;
    private Date evtFechaEli;

    public Evento() {
    }

    public Evento(int idTipoevento, int idPeriodo, String evtNombre, Date evtFecha, int evtDistrito, int evtIglesia, int evtUsuAdd, Date evtFechaAdd) {
        this.idTipoevento = idTipoevento;
        this.idPeriodo = idPeriodo;
        this.evtNombre = evtNombre;
        this.evtFecha = evtFecha;
        this.evtDistrito = evtDistrito;
        this.evtIglesia = evtIglesia;
        this.evtUsuAdd = evtUsuAdd;
        this.evtFechaAdd = evtFechaAdd;
    }

    public Evento(int idTipoevento, int idPeriodo, String evtNombre, String evtDescripcion, String evtLugar, Date evtFecha, Date evtFechaLimite, int evtDistrito, int evtIglesia, String evtEstado, int evtUsuAdd, Integer evtUsuUpd, Integer evtUsuEli, Date evtFechaAdd, Date evtFechaUpd, Date evtFechaEli) {
        this.idTipoevento = idTipoevento;
        this.idPeriodo = idPeriodo;
        this.evtNombre = evtNombre;
        this.evtDescripcion = evtDescripcion;
        this.evtLugar = evtLugar;
        this.evtFecha = evtFecha;
        this.evtFechaLimite = evtFechaLimite;
        this.evtDistrito = evtDistrito;
        this.evtIglesia = evtIglesia;
        this.evtEstado = evtEstado;
        this.evtUsuAdd = evtUsuAdd;
        this.evtUsuUpd = evtUsuUpd;
        this.evtUsuEli = evtUsuEli;
        this.evtFechaAdd = evtFechaAdd;
        this.evtFechaUpd = evtFechaUpd;
        this.evtFechaEli = evtFechaEli;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idEVENTO", unique = true, nullable = false)
    public Integer getIdEvento() {
        return this.idEvento;
    }

    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    @Column(name = "idTIPOEVENTO", nullable = false)
    public int getIdTipoevento() {
        return this.idTipoevento;
    }

    public void setIdTipoevento(int idTipoevento) {
        this.idTipoevento = idTipoevento;
    }

    @Column(name = "idPERIODO", nullable = false)
    public int getIdPeriodo() {
        return this.idPeriodo;
    }

    public void setIdPeriodo(int idPeriodo) {
        this.idPeriodo = idPeriodo;
    }

    @Column(name = "EVT_NOMBRE", nullable = false, length = 64)
    public String getEvtNombre() {
        return this.evtNombre;
    }

    public void setEvtNombre(String evtNombre) {
        this.evtNombre = evtNombre;
    }

    @Column(name = "EVT_DESCRIPCION")
    public String getEvtDescripcion() {
        return this.evtDescripcion;
    }

    public void setEvtDescripcion(String evtDescripcion) {
        this.evtDescripcion = evtDescripcion;
    }

    @Column(name = "EVT_LUGAR")
    public String getEvtLugar() {
        return this.evtLugar;
    }

    public void setEvtLugar(String evtLugar) {
        this.evtLugar = evtLugar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EVT_FECHA", nullable = false, length = 19)
    public Date getEvtFecha() {
        return this.evtFecha;
    }

    public void setEvtFecha(Date evtFecha) {
        this.evtFecha = evtFecha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EVT_FECHA_LIMITE", length = 19)
    public Date getEvtFechaLimite() {
        return this.evtFechaLimite;
    }

    public void setEvtFechaLimite(Date evtFechaLimite) {
        this.evtFechaLimite = evtFechaLimite;
    }

    @Column(name = "EVT_DISTRITO", nullable = false)
    public int getEvtDistrito() {
        return this.evtDistrito;
    }

    public void setEvtDistrito(int evtDistrito) {
        this.evtDistrito = evtDistrito;
    }

    @Column(name = "EVT_IGLESIA", nullable = false)
    public int getEvtIglesia() {
        return this.evtIglesia;
    }

    public void setEvtIglesia(int evtIglesia) {
        this.evtIglesia = evtIglesia;
    }

    @Column(name = "EVT_ESTADO", length = 1)
    public String getEvtEstado() {
        return this.evtEstado;
    }

    public void setEvtEstado(String evtEstado) {
        this.evtEstado = evtEstado;
    }

    @Column(name = "EVT_USU_ADD", nullable = false)
    public int getEvtUsuAdd() {
        return this.evtUsuAdd;
    }

    public void setEvtUsuAdd(int evtUsuAdd) {
        this.evtUsuAdd = evtUsuAdd;
    }

    @Column(name = "EVT_USU_UPD")
    public Integer getEvtUsuUpd() {
        return this.evtUsuUpd;
    }

    public void setEvtUsuUpd(Integer evtUsuUpd) {
        this.evtUsuUpd = evtUsuUpd;
    }

    @Column(name = "EVT_USU_ELI")
    public Integer getEvtUsuEli() {
        return this.evtUsuEli;
    }

    public void setEvtUsuEli(Integer evtUsuEli) {
        this.evtUsuEli = evtUsuEli;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EVT_FECHA_ADD", nullable = false, length = 19)
    public Date getEvtFechaAdd() {
        return this.evtFechaAdd;
    }

    public void setEvtFechaAdd(Date evtFechaAdd) {
        this.evtFechaAdd = evtFechaAdd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EVT_FECHA_UPD", length = 19)
    public Date getEvtFechaUpd() {
        return this.evtFechaUpd;
    }

    public void setEvtFechaUpd(Date evtFechaUpd) {
        this.evtFechaUpd = evtFechaUpd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EVT_FECHA_ELI", length = 19)
    public Date getEvtFechaEli() {
        return this.evtFechaEli;
    }

    public void setEvtFechaEli(Date evtFechaEli) {
        this.evtFechaEli = evtFechaEli;
    }

}
