package pe.edu.upeu.crm.bean;
// Generated 11/11/2017 08:16:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventogrupoId generated by hbm2java
 */
@Embeddable
public class EventogrupoId implements java.io.Serializable {

    private int idGrupo;
    private int idEvento;

    public EventogrupoId() {
    }

    public EventogrupoId(int idGrupo, int idEvento) {
        this.idGrupo = idGrupo;
        this.idEvento = idEvento;
    }

    @Column(name = "idGRUPO", nullable = false)
    public int getIdGrupo() {
        return this.idGrupo;
    }

    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }

    @Column(name = "idEVENTO", nullable = false)
    public int getIdEvento() {
        return this.idEvento;
    }

    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof EventogrupoId)) {
            return false;
        }
        EventogrupoId castOther = (EventogrupoId) other;

        return (this.getIdGrupo() == castOther.getIdGrupo())
                && (this.getIdEvento() == castOther.getIdEvento());
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 37 * result + this.getIdGrupo();
        result = 37 * result + this.getIdEvento();
        return result;
    }

}
