package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 11:55:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Iglesia generated by hbm2java
 */
@Entity
@Table(name="iglesia"
    ,catalog="dbcrm"
)
public class Iglesia  implements java.io.Serializable {


     private Integer idIglesia;
     private Distrito distrito;
     private String iglNombre;
     private Date iglFechaCreacion;
     private String iglEstado;
     private String iglDireccion;
     private Set<Ministerio> ministerios = new HashSet<Ministerio>(0);
     private Set<Escuela> escuelas = new HashSet<Escuela>(0);

    public Iglesia() {
    }

	
    public Iglesia(Distrito distrito, String iglNombre, Date iglFechaCreacion, String iglEstado) {
        this.distrito = distrito;
        this.iglNombre = iglNombre;
        this.iglFechaCreacion = iglFechaCreacion;
        this.iglEstado = iglEstado;
    }
    public Iglesia(Distrito distrito, String iglNombre, Date iglFechaCreacion, String iglEstado, String iglDireccion, Set<Ministerio> ministerios, Set<Escuela> escuelas) {
       this.distrito = distrito;
       this.iglNombre = iglNombre;
       this.iglFechaCreacion = iglFechaCreacion;
       this.iglEstado = iglEstado;
       this.iglDireccion = iglDireccion;
       this.ministerios = ministerios;
       this.escuelas = escuelas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIGLESIA", unique=true, nullable=false)
    public Integer getIdIglesia() {
        return this.idIglesia;
    }
    
    public void setIdIglesia(Integer idIglesia) {
        this.idIglesia = idIglesia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDISTRITO", nullable=false)
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="IGL_NOMBRE", nullable=false, length=64)
    public String getIglNombre() {
        return this.iglNombre;
    }
    
    public void setIglNombre(String iglNombre) {
        this.iglNombre = iglNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="IGL_FECHA_CREACION", nullable=false, length=10)
    public Date getIglFechaCreacion() {
        return this.iglFechaCreacion;
    }
    
    public void setIglFechaCreacion(Date iglFechaCreacion) {
        this.iglFechaCreacion = iglFechaCreacion;
    }

    
    @Column(name="IGL_ESTADO", nullable=false, length=1)
    public String getIglEstado() {
        return this.iglEstado;
    }
    
    public void setIglEstado(String iglEstado) {
        this.iglEstado = iglEstado;
    }

    
    @Column(name="IGL_DIRECCION")
    public String getIglDireccion() {
        return this.iglDireccion;
    }
    
    public void setIglDireccion(String iglDireccion) {
        this.iglDireccion = iglDireccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iglesia")
    public Set<Ministerio> getMinisterios() {
        return this.ministerios;
    }
    
    public void setMinisterios(Set<Ministerio> ministerios) {
        this.ministerios = ministerios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iglesia")
    public Set<Escuela> getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set<Escuela> escuelas) {
        this.escuelas = escuelas;
    }




}


