package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 11:55:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Miembromin generated by hbm2java
 */
@Entity
@Table(name="miembromin"
    ,catalog="dbcrm"
)
public class Miembromin  implements java.io.Serializable {


     private Integer idMiembromin;
     private Ministerio ministerio;
     private Persona persona;
     private Date mmiFechaRegistro;
     private String mmiEstado;
     private Set<Asmiemmin> asmiemmins = new HashSet<Asmiemmin>(0);

    public Miembromin() {
    }

	
    public Miembromin(Ministerio ministerio, Persona persona) {
        this.ministerio = ministerio;
        this.persona = persona;
    }
    public Miembromin(Ministerio ministerio, Persona persona, Date mmiFechaRegistro, String mmiEstado, Set<Asmiemmin> asmiemmins) {
       this.ministerio = ministerio;
       this.persona = persona;
       this.mmiFechaRegistro = mmiFechaRegistro;
       this.mmiEstado = mmiEstado;
       this.asmiemmins = asmiemmins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMIEMBROMIN", unique=true, nullable=false)
    public Integer getIdMiembromin() {
        return this.idMiembromin;
    }
    
    public void setIdMiembromin(Integer idMiembromin) {
        this.idMiembromin = idMiembromin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMINISTERIO", nullable=false)
    public Ministerio getMinisterio() {
        return this.ministerio;
    }
    
    public void setMinisterio(Ministerio ministerio) {
        this.ministerio = ministerio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MMI_FECHA_REGISTRO", length=19)
    public Date getMmiFechaRegistro() {
        return this.mmiFechaRegistro;
    }
    
    public void setMmiFechaRegistro(Date mmiFechaRegistro) {
        this.mmiFechaRegistro = mmiFechaRegistro;
    }

    
    @Column(name="MMI_ESTADO", length=1)
    public String getMmiEstado() {
        return this.mmiEstado;
    }
    
    public void setMmiEstado(String mmiEstado) {
        this.mmiEstado = mmiEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="miembromin")
    public Set<Asmiemmin> getAsmiemmins() {
        return this.asmiemmins;
    }
    
    public void setAsmiemmins(Set<Asmiemmin> asmiemmins) {
        this.asmiemmins = asmiemmins;
    }




}


