package pe.edu.upeu.crm.bean;
// Generated 11/11/2017 08:16:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name="periodo"
    ,catalog="dbcrm"
)
public class Periodo  implements java.io.Serializable {


     private Integer idPeriodo;
     private String prdNombre;
     private Date prdFechaInicio;
     private Date prdFechaLimite;
     private int prdDistrito;
     private int prdIglesia;
     private String prdEstado;
     private Set<Evento> eventos = new HashSet<Evento>(0);

    public Periodo() {
    }

	
    public Periodo(String prdNombre, Date prdFechaInicio, Date prdFechaLimite, int prdDistrito, int prdIglesia, String prdEstado) {
        this.prdNombre = prdNombre;
        this.prdFechaInicio = prdFechaInicio;
        this.prdFechaLimite = prdFechaLimite;
        this.prdDistrito = prdDistrito;
        this.prdIglesia = prdIglesia;
        this.prdEstado = prdEstado;
    }
    public Periodo(String prdNombre, Date prdFechaInicio, Date prdFechaLimite, int prdDistrito, int prdIglesia, String prdEstado, Set<Evento> eventos) {
       this.prdNombre = prdNombre;
       this.prdFechaInicio = prdFechaInicio;
       this.prdFechaLimite = prdFechaLimite;
       this.prdDistrito = prdDistrito;
       this.prdIglesia = prdIglesia;
       this.prdEstado = prdEstado;
       this.eventos = eventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPERIODO", unique=true, nullable=false)
    public Integer getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(Integer idPeriodo) {
        this.idPeriodo = idPeriodo;
    }

    
    @Column(name="PRD_NOMBRE", nullable=false, length=64)
    public String getPrdNombre() {
        return this.prdNombre;
    }
    
    public void setPrdNombre(String prdNombre) {
        this.prdNombre = prdNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PRD_FECHA_INICIO", nullable=false, length=10)
    public Date getPrdFechaInicio() {
        return this.prdFechaInicio;
    }
    
    public void setPrdFechaInicio(Date prdFechaInicio) {
        this.prdFechaInicio = prdFechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PRD_FECHA_LIMITE", nullable=false, length=10)
    public Date getPrdFechaLimite() {
        return this.prdFechaLimite;
    }
    
    public void setPrdFechaLimite(Date prdFechaLimite) {
        this.prdFechaLimite = prdFechaLimite;
    }

    
    @Column(name="PRD_DISTRITO", nullable=false)
    public int getPrdDistrito() {
        return this.prdDistrito;
    }
    
    public void setPrdDistrito(int prdDistrito) {
        this.prdDistrito = prdDistrito;
    }

    
    @Column(name="PRD_IGLESIA", nullable=false)
    public int getPrdIglesia() {
        return this.prdIglesia;
    }
    
    public void setPrdIglesia(int prdIglesia) {
        this.prdIglesia = prdIglesia;
    }

    
    @Column(name="PRD_ESTADO", nullable=false, length=1)
    public String getPrdEstado() {
        return this.prdEstado;
    }
    
    public void setPrdEstado(String prdEstado) {
        this.prdEstado = prdEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodo")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }




}


