package pe.edu.upeu.crm.bean;
// Generated 09/11/2017 08:15:47 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Personaevento generated by hbm2java
 */
@Entity
@Table(name="personaevento"
    ,catalog="dbcrm"
)
public class Personaevento  implements java.io.Serializable {


     private PersonaeventoId id;
     private String asistecia;

    public Personaevento() {
    }

	
    public Personaevento(PersonaeventoId id) {
        this.id = id;
    }
    public Personaevento(PersonaeventoId id, String asistecia) {
       this.id = id;
       this.asistecia = asistecia;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPersona", column=@Column(name="idPERSONA", nullable=false) ), 
        @AttributeOverride(name="idEvento", column=@Column(name="idEVENTO", nullable=false) ) } )
    public PersonaeventoId getId() {
        return this.id;
    }
    
    public void setId(PersonaeventoId id) {
        this.id = id;
    }

    
    @Column(name="ASISTECIA", length=1)
    public String getAsistecia() {
        return this.asistecia;
    }
    
    public void setAsistecia(String asistecia) {
        this.asistecia = asistecia;
    }




}


