package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 11:55:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="dbcrm"
)
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private Documento documento;
     private String perNombres;
     private String perApellidos;
     private String perDocumento;
     private Date perFecNacimiento;
     private String perCorreo;
     private String perDireccion;
     private String perTelefono;
     private String perBautizado;
     private String perSexo;
     private Date perFechaBautismo;
     private String perFoto;
     private Set<Miembromin> miembromins = new HashSet<Miembromin>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Miembrogp> miembrogps = new HashSet<Miembrogp>(0);

    public Persona() {
    }

	
    public Persona(Documento documento, String perNombres, String perApellidos, String perDocumento, String perBautizado, String perSexo) {
        this.documento = documento;
        this.perNombres = perNombres;
        this.perApellidos = perApellidos;
        this.perDocumento = perDocumento;
        this.perBautizado = perBautizado;
        this.perSexo = perSexo;
    }
    public Persona(Documento documento, String perNombres, String perApellidos, String perDocumento, Date perFecNacimiento, String perCorreo, String perDireccion, String perTelefono, String perBautizado, String perSexo, Date perFechaBautismo, String perFoto, Set<Miembromin> miembromins, Set<Usuario> usuarios, Set<Miembrogp> miembrogps) {
       this.documento = documento;
       this.perNombres = perNombres;
       this.perApellidos = perApellidos;
       this.perDocumento = perDocumento;
       this.perFecNacimiento = perFecNacimiento;
       this.perCorreo = perCorreo;
       this.perDireccion = perDireccion;
       this.perTelefono = perTelefono;
       this.perBautizado = perBautizado;
       this.perSexo = perSexo;
       this.perFechaBautismo = perFechaBautismo;
       this.perFoto = perFoto;
       this.miembromins = miembromins;
       this.usuarios = usuarios;
       this.miembrogps = miembrogps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPERSONA", unique=true, nullable=false)
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDOCUMENTO", nullable=false)
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }

    
    @Column(name="PER_NOMBRES", nullable=false, length=64)
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }

    
    @Column(name="PER_APELLIDOS", nullable=false, length=64)
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }

    
    @Column(name="PER_DOCUMENTO", nullable=false, length=15)
    public String getPerDocumento() {
        return this.perDocumento;
    }
    
    public void setPerDocumento(String perDocumento) {
        this.perDocumento = perDocumento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PER_FEC_NACIMIENTO", length=10)
    public Date getPerFecNacimiento() {
        return this.perFecNacimiento;
    }
    
    public void setPerFecNacimiento(Date perFecNacimiento) {
        this.perFecNacimiento = perFecNacimiento;
    }

    
    @Column(name="PER_CORREO", length=128)
    public String getPerCorreo() {
        return this.perCorreo;
    }
    
    public void setPerCorreo(String perCorreo) {
        this.perCorreo = perCorreo;
    }

    
    @Column(name="PER_DIRECCION")
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }

    
    @Column(name="PER_TELEFONO", length=20)
    public String getPerTelefono() {
        return this.perTelefono;
    }
    
    public void setPerTelefono(String perTelefono) {
        this.perTelefono = perTelefono;
    }

    
    @Column(name="PER_BAUTIZADO", nullable=false, length=1)
    public String getPerBautizado() {
        return this.perBautizado;
    }
    
    public void setPerBautizado(String perBautizado) {
        this.perBautizado = perBautizado;
    }

    
    @Column(name="PER_SEXO", nullable=false, length=1)
    public String getPerSexo() {
        return this.perSexo;
    }
    
    public void setPerSexo(String perSexo) {
        this.perSexo = perSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PER_FECHA_BAUTISMO", length=10)
    public Date getPerFechaBautismo() {
        return this.perFechaBautismo;
    }
    
    public void setPerFechaBautismo(Date perFechaBautismo) {
        this.perFechaBautismo = perFechaBautismo;
    }

    
    @Column(name="PER_FOTO")
    public String getPerFoto() {
        return this.perFoto;
    }
    
    public void setPerFoto(String perFoto) {
        this.perFoto = perFoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Miembromin> getMiembromins() {
        return this.miembromins;
    }
    
    public void setMiembromins(Set<Miembromin> miembromins) {
        this.miembromins = miembromins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Miembrogp> getMiembrogps() {
        return this.miembrogps;
    }
    
    public void setMiembrogps(Set<Miembrogp> miembrogps) {
        this.miembrogps = miembrogps;
    }




}


