package pe.edu.upeu.crm.bean;
// Generated 05/10/2017 07:39:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unionp generated by hbm2java
 */
@Entity
@Table(name="unionp"
    ,catalog="dbcrm"
)
public class Unionp  implements java.io.Serializable {


     private Integer idUnion;
     private String uniNombre;
     private Date uniFechaCreacion;
     private String uniEstado;
     private Set<Campo> campos = new HashSet<Campo>(0);

    public Unionp() {
    }

	
    public Unionp(String uniNombre, Date uniFechaCreacion, String uniEstado) {
        this.uniNombre = uniNombre;
        this.uniFechaCreacion = uniFechaCreacion;
        this.uniEstado = uniEstado;
    }
    public Unionp(String uniNombre, Date uniFechaCreacion, String uniEstado, Set<Campo> campos) {
       this.uniNombre = uniNombre;
       this.uniFechaCreacion = uniFechaCreacion;
       this.uniEstado = uniEstado;
       this.campos = campos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUNION", unique=true, nullable=false)
    public Integer getIdUnion() {
        return this.idUnion;
    }
    
    public void setIdUnion(Integer idUnion) {
        this.idUnion = idUnion;
    }

    
    @Column(name="UNI_NOMBRE", nullable=false, length=64)
    public String getUniNombre() {
        return this.uniNombre;
    }
    
    public void setUniNombre(String uniNombre) {
        this.uniNombre = uniNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UNI_FECHA_CREACION", nullable=false, length=10)
    public Date getUniFechaCreacion() {
        return this.uniFechaCreacion;
    }
    
    public void setUniFechaCreacion(Date uniFechaCreacion) {
        this.uniFechaCreacion = uniFechaCreacion;
    }

    
    @Column(name="UNI_ESTADO", nullable=false, length=1)
    public String getUniEstado() {
        return this.uniEstado;
    }
    
    public void setUniEstado(String uniEstado) {
        this.uniEstado = uniEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unionp")
    public Set<Campo> getCampos() {
        return this.campos;
    }
    
    public void setCampos(Set<Campo> campos) {
        this.campos = campos;
    }




}


